name: Jenkins Build with Parameters and Monitor
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Build single job
      uses: Mondtic/build-jenkins-job@master
      with:
        jenkins-url: 'https://jenkins-ai.tesla.com/job/eval/buildWithParameters?token=116b9b69083ed7dfc08877ac0fe5646c86'
        jenkins-token: '116b9b69083ed7dfc08877ac0fe5646c86'
        jenkins-user: 'bhausleitner'
        jenkins-job: ${{ secrets.JENKINS_JOB }}
        jenkins-job-params: "{'GIT_BRANCH': 'master', 'ENV': 'dev'}"
        jenkins-wait-job: "no-wait"
        jenkins-ssl-verify: "true"
        
