name: Jenkins Build with Parameters and Monitor
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://jenkins-ai.tesla.com/job/eval/buildWithParameters?token=116b9b69083ed7dfc08877ac0fe5646c86'
        method: 'POST'
        username: "bhausleitner"
        password: "116b9b69083ed7dfc08877ac0fe5646c86"
        data: '{"GIT_BRANCH": "master", "ENV": "dev"}'
        
