
name: Jenkins Build and Monitor
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Jenkins Build
      run: curl -i https://jenkins-ai.tesla.com/job/eval/buildWithParameters?token=116b9b69083ed7dfc08877ac0fe5646c86 -F GIT_BRANCH=master -F ENV=dev --user bhausleitner:116b9b69083ed7dfc08877ac0fe5646c86
        
