
name: Jenkins Build and Monitor
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Make API Request
      run: |
        RESPONSE=$(curl -X POST "https://api.coindesk.com/v1/bpi/currentprice.json" -H "Content-Type: application/json")
        LOCATION=$(echo "$RESPONSE" | grep -i time | awk '{print $2}')
        echo "::set-env name=LOCATION::$LOCATION"

    - name: Print Location
      run: echo "$LOCATION"
