
name: Jenkins Build and Monitor
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Jenkins Build
      run: curl -X GET https://api.coindesk.com/v1/bpi/currentprice.json
        
    - name: GET all workspace
      run: | 
          curl --location --request GET 'https://api.coindesk.com/v1/bpi/currentprice.json' -o workspaces.json

    - name: read workspace id
      id: workspace 
      run: echo "::set-output name=id::$(cat workspaces.json | jq -c '.workspaces[] | select(.name == "time")')"

    - name: print workspace id
      run: echo ${{ steps.workspace.outputs.id }}

  

    
